steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', 'deployment', '${_DEPLOYMENTNAME}','--image=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: nice-gate-272207
    _ZONE: us-central1-c
    _GKE_CLUSTER: cluster-1	

#Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: hello-world-service-vino   
    _REPO_NAME: github_vinodhini-devops_cloudbuild
    
    # Developers ONLY change
    _VERSION: v1.0
    

